"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
var why_icon1_png_1 = __importDefault(require("../assets/img/why-icon1.png"));
var why_icon2_png_1 = __importDefault(require("../assets/img/why-icon2.png"));
var why_icon3_png_1 = __importDefault(require("../assets/img/why-icon3.png"));
var why_icon4_png_1 = __importDefault(require("../assets/img/why-icon4.png"));
var WhyUsSection = function () {
    return ((0, jsx_runtime_1.jsx)("section", { id: "why-us", className: "py-12 bg-[#ffffff]", children: (0, jsx_runtime_1.jsxs)("div", { className: "container mx-auto space-y-4 p-4 lg:p-0", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-2xl font-bold", children: "Why Us?" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm font-light", children: "Mengapa harus pilih Binar Car Rental?" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col lg:flex-row gap-8 pt-8", children: [(0, jsx_runtime_1.jsxs)("div", { className: "w-full lg:w-3/12 p-6 px-8 space-y-4 border-2 shadow-md transition-all duration-500 ease-in-out hover:cursor-pointer hover:text-[#000000] hover:scale-110", children: [(0, jsx_runtime_1.jsx)("img", { src: why_icon1_png_1.default, alt: "icon_1", className: "w-[32px]" }), (0, jsx_runtime_1.jsx)("h3", { className: "text-base font-bold", children: "Mobil Lengkap" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm font-light text-slate-700", children: "Tersedia banyak pilihan mobil, kondisi masih baru, bersih dan terawat" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "w-full lg:w-3/12 p-6 px-8 space-y-4 border-2 shadow-md transition-all duration-500 ease-in-out hover:cursor-pointer hover:scale-110", children: [(0, jsx_runtime_1.jsx)("img", { src: why_icon2_png_1.default, alt: "icon_2", className: "w-[32px]" }), (0, jsx_runtime_1.jsx)("h3", { className: "text-base font-bold", children: "Harga Murah" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm font-light text-slate-700", children: "Harga murah dan bersaing, bisa bandingkan harga kami dengan rental mobil lain" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "w-full lg:w-3/12 p-6 px-8 space-y-4 border-2 shadow-md transition-all duration-500 ease-in-out hover:cursor-pointer hover:scale-110", children: [(0, jsx_runtime_1.jsx)("img", { src: why_icon3_png_1.default, alt: "icon_3", className: "w-[32px]" }), (0, jsx_runtime_1.jsx)("h3", { className: "text-base font-bold", children: "Layanan 24 Jam" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm font-light text-slate-700", children: "Siap melayani kebutuhan Anda selama 24 jam nonstop. Kami juga tersedia di akhir minggu" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "w-full lg:w-3/12 p-6 px-8 space-y-4 border-2 shadow-md transition-all duration-500 ease-in-out hover:cursor-pointer hover:scale-110", children: [(0, jsx_runtime_1.jsx)("img", { src: why_icon4_png_1.default, alt: "icon_4", className: "w-[32px]" }), (0, jsx_runtime_1.jsx)("h3", { className: "text-base font-bold", children: "Sopir Profesional" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm font-light text-slate-700", children: "Sopir yang profesional, berpengalaman, jujur, ramah dan selalu tepat waktu" })] })] })] }) }));
};
exports.default = WhyUsSection;
